### PR TITLE
2022-Nov-14/updates: nvim-scrollbar gitsigns

### PR DESCRIPTION
**Pull request by Gelio**
Add nvim-scrollbar gaining gitsigns support as an update.

### CODE REVIEW

**Comment by phaazon** [comment]
Please do not remove examples. It can be used by other people.

**Review by phaazon — CHANGES_REQUESTED** [review]
Please do not remove examples. It can be used by other people.

**Comment by Gelio** [comment]
Sure. I missed that information in the contributing section of the readme. In that case, should I leave it as `1-example.md` alongside the file I added?

**Comment by Gelio** [comment]
I reverted the removal of `1-example.md`

**Review by phaazon — APPROVED** [review]

**Pull request merged**
