### PR TITLE
Add document-color.nvim as a new plugin

### PR DESCRIPTION
**Pull request by mrshmllow**
Hope its okay to add OC!!

### CODE REVIEW

**Review by phaazon — CHANGES_REQUESTED** [review]
Of course it is! Can you please rebase your work on `2022-Aug-22` and fix the conflicts, as other PRs got merged. I will merge as soon as you have fixed the conflicts. :blush:

**Comment by mrshmllow** [comment]
I think i fixed the conflict. I cant access `git` right now

**Comment by phaazon** [comment]
Thank you, I will do the rebase.

**Comment by phaazon** [comment]
:thinking: something went wrong while merging. I will cherry pick the commits.

**Comment by mrshmllow** [comment]
yep, github is weird. sorry!!

**Pull request merged**
