### PR TITLE
Added tip about auto-toggle hlsearch

### PR DESCRIPTION
**Pull request by Wansmer**
Hi! I am already posted that tip on [reddit](https://www.reddit.com/r/neovim/comments/zc720y/tip_to_manage_hlsearch/). This is an optimized version of tip by **Mhalter3378's** [comment](https://www.reddit.com/r/neovim/comments/zc720y/comment/iyvcdf0/?utm_source=share&utm_medium=web2x&context=3).

### CODE REVIEW

**Review by phaazon — CHANGES_REQUESTED** [review]
Thanks for contributing! However, that was already shared in the previous week, so I’m not sure what to do. We’ll wait to see if other tips are shared and if not, may I ask you to change a bit your next to reference [this](https://this-week-in-neovim.org/2023/Jan/02#tips) as a context introduction? Thanks!

**Comment by Wansmer** [comment]
In last week, I shared a tip about setting cursor to last exiting place. Now it another tip about manage hlsearch :-) It is two different tips.

**Comment by phaazon** [comment]
> > that was already shared in the previous week
> 
> In last week, I shared a tip about setting cursor to last exiting place. Now it another tip about manage hlsearch :-) It is two different tips.

Right, it’s slightly different I agree. Can you just add a link like « Last week we saw… » and link to it? Thanks!

**Comment by Wansmer** [comment]
> Right, it’s slightly different I agree. Can you just add a link like « Last week we saw… » and link to it? Thanks!

I change text and added link on previous week tip.
English not my native language and I can do mistakes in text. If you think what this tip required another text – please, change it yourself or just close PR.

**Review by phaazon — APPROVED** [review]

**Pull request merged**
