### PR TITLE
Add pvim to 2022-Aug-08.

### PR DESCRIPTION
**Pull request by phaazon**

### CODE REVIEW

**Comment by phaazon** [comment]
Will not merge unless explicit approval by @RoryNesbitt.

**Comment by RoryNesbitt** [comment]
It's not perfect yet but it's good enough to let people try it.

[Reddit announcement](https://www.reddit.com/r/neovim/comments/whrsrb/introducing_pvim_a_portable_neovim_wrapper/)

**Comment by RoryNesbitt** [comment]
Can we add a comment about containing everything to a single directory. Just to better explain what it's use case is

And that the seanvim name is in reference to how much help Sean put in to getting it working 😊

**Comment by phaazon** [comment]
Sure.

**Comment by phaazon** [comment]
Alright, I added your comment @RoryNesbitt. I’m merging so that it gets released tomorrow with the rest of the news. :slightly_smiling_face:

**Comment by RoryNesbitt** [comment]
Sounds great. Thanks for including it

**Pull request merged**
